# Generated by Django 5.2.7 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_file_url',
            field=models.URLField(blank=True, help_text='Cloudinary CV URL', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', null=True),
        ),
    ]
