# Generated by Django 5.2.7 on 2025-11-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_cv_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.URLField(blank=True, help_text='Paste your CV Google Drive/Cloud link', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Paste Cloudinary Image URL', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='Paste Cloudinary Image URL', null=True),
        ),
    ]
